### PR TITLE
make -v option work

### LINKED ISSUE #94: [BUG] make build
**command line option  -v, the output is always 1.0.1**

run `bin/teler -v`  the output is always
```sh
$ bin/teler -v
teler 1.0.1
```
cause the version varibale defined in [constants.go](https://github.com/kitabisa/teler/blob/62623bcb3d6071f8c96d816980a36906b402e659/internal/runner/constants.go#L5) **is not overwritten** at build time in [Makefile](https://github.com/kitabisa/teler/blob/62623bcb3d/Makefile#L30)

**To Reproduce**
just clone the repo, and run `make build` to compile the binary, then run `bin/teler -v`
the output is always 
```sh
$ bin/teler -v
teler 1.0.1
```

**Expected behavior**
at this time, the output version should be
```sh
 bin/teler -v
teler v1.0.1-29-g62623bc
```
if we tag a new commit, the `-v` option should produce a new version

**Screenshots**
sorry for my company network environment, I can just describe in text

**Environment:**
I think this bug should reproduce in all OS
I am using windows10 and git-bash
- OS: [windows10]
- OS version: [windows10]
- teler Version the problem is about version, so ........

### PR DESCRIPTION
**Pull request by brownchow**
### Proposed of changes

This PR fixes #94 

Hi all: 
1. we use [-ldflags "-X  importpath.name=value"](https://golang.org/cmd/link/)  option to modify the value of the Version, and then when we type `teler -v`, the program just print the version we passed in, but I can't find a suitable way to modify the version variable defined in [version](https://github.com/kitabisa/teler/blob/62623bcb3d6071f8c96d816980a36906b402e659/internal/runner/constants.go#L5), so I referenced [this repository](https://github.com/juicedata/juicesync/blob/master/Makefile), and make a new directory versioninfo, define the Version varibale there.  If you find a better way to modify the [version](https://github.com/kitabisa/teler/blob/62623bcb3d6071f8c96d816980a36906b402e659/internal/runner/constants.go#L5), CORRECT ME!

2. as the [GoDoc](https://golang.org/cmd/link/) says:
```sh
 -X importpath.name=value
Set the value of the string variable in importpath named name to value.
This is only effective if the variable is declared in the source code either uninitialized
or initialized to a constant string expression. -X will not work if the initializer makes
a function call or refers to other variables.
Note that before Go 1.5 this option took two separate arguments.
```
I found there is no variables  `GitCommit`  `Environment`  `BuildDate` defined in source code, so there is no need to keep them and related variables.

3. I added `-ldflags "-s"` in the Makefile,  as the [GoDoc](https://golang.org/cmd/link/) says:
```sh
 -s  Omit the symbol table and debug information.
```
this can make binary executable file **smaller**, we DON'T need the symbol table and debug information  when delivering a binary release.

to prove this, I'm doing the following on windows10 and using git-bash
- with `-ldflags "-s"`
```sh
/d/golang/src/github.com/kisielk/teler (master)
$ make  build
Building teler v1.0.1-29-g62623bc
GOPATH=d:\golang
go build -ldflags "-s -w  -X ktbs.dev/teler/versioninfo.Version=v1.0.1-29-g62623bc" -o ./bin/teler ./cmd/teler

$ du -sh bin/teler
12M     bin/teler
```

- without `-ldflags "-s"`
```sh
 /d/golang/src/github.com/kisielk/teler (master)
$ make  build
Building teler v1.0.1-29-g62623bc
GOPATH=d:\golang
go build -ldflags "-w  -X ktbs.dev/teler/versioninfo.Version=v1.0.1-29-g62623bc" -o ./bin/teler ./cmd/teler

$ du -sh bin/teler
13M     bin/teler
```
we save **1MB** disk space!

### CODE REVIEW

**Comment by dwisiswant0** [comment]
Nice catch, @brownchow! We'll review as soon as possible.

**Comment by dwisiswant0** [comment]
Can you please rebase it, @brownchow?

**Comment by brownchow** [comment]
> Can you please rebase it, @brownchow?

just rebased it

**Comment by dwisiswant0** [comment]
Hi @brownchow,

Before we merging this. Please note that we use [goreleaser GitHub action](https://github.com/goreleaser/goreleaser-action) to make an automatic release. Can you confirm this code deal these needs? See our [workflow here](https://github.com/kitabisa/teler/blob/master/.github/workflows/release.yaml).

**Review by dwisiswant0 — APPROVED** [review]
Superlative work, @brownchow! We'll merge it to `master` and refactor this a bit to apply goreleaser GitHub Actions.

**Comment by dwisiswant0** [comment]
@all-contributors add @brownchow for code.

**Pull request merged**
