### PR TITLE
simplify Dockerflie

### LINKED ISSUE #78: [BUG]
**Describe the bug**

maybe this is not a bug, but I can't find a suitable classification of this issue. 

the Dockerfile add a **useless** instruction `RUN mkdir -p /app`
just as the  [docker documentation](https://docs.docker.com/engine/reference/builder/#workdir) says: If the WORKDIR doesn’t exist, it will be created, so there is no need to add this insctruction before `WORKDIR /app`, but if you indeed want to add it, it works fine!
so leave it or not?  it's up to you.

And for linux platform, the `go bulld` produced binary wasn't added to .gitignore

**To Reproduce**

nothing

```yaml
Your teler config file...
// Please redacted your token and/ other sensitive informations
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- OS: [e.g. mac, linux]
- OS version: [uname -a]
- teler Version [teler --version]

**Additional context**
Add any other context about the problem here. Full output log is probably a helpful thing to add here.

### PR DESCRIPTION
**Pull request by brownchow**
**IMPORTANT: Please do not create a Pull Request without creating an issue first!**

_(Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request)._

### Summary

_Explains the information and/ motivation for making this changes..._

### Proposed of changes

This PR fixes/implements the following **bugs/features**:

- Bug 1
- Bug 2
- Feature 1
- Feature 2
- Breaking changes

### How has this been tested?

Proof:

### Closing issues

Fixes #78

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [x] I have followed the guidelines in our [CONTRIBUTING.md](https://github.com/kitabisa/teler/blob/development/.github/CONTRIBUTING.md) document.
- [x] I have written new tests for my changes.
  - [x] My changes successfully ran and pass tests locally.

### CODE REVIEW

**Comment by dwisiswant0** [comment]
Nice catch, @brownchow! Please leave `.gitignore` values as before, as we provide instructions for create binary file with `make build`.
Oh, and - please cross the checklists on this summary.

**Comment by brownchow** [comment]
> Nice catch, @brownchow! Please leave `.gitignore` values as before, as we provide instructions for create binary file with `make build`.
> Oh, and - please cross the checklists on this summary.

I have reset .gitignore, and cross the chicklist, I just delete a line in Dockerfile, It seems there is nothing to do.

**Review by dwisiswant0 — APPROVED** [review]
LGTM! :man_dancing:

**Comment by dwisiswant0** [comment]
@all-contributors please add @brownchow for maintenance.

**Pull request merged**
